name: Main ReadMe Updater

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'

jobs:
  UpdateMainReadmeTemplate:
    runs-on: ubuntu-latest

    steps:
      - name: 🎏 Fetch repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ✨ Create ReadMe.md
        run: |
          cd ${GITHUB_WORKSPACE}/
          npm i
          node src/update.js
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "[Automatic] Updated ReadMe.md"
          git push --all -f https://${{ secrets.TOKEN_GITHUB }}@github.com/${GITHUB_REPOSITORY}.git
